<script setup>
import { stringifyExpression } from '@vue/compiler-core';
import { ref, computed } from 'vue'

const emit = defineEmits(['glyph'])

const filterChar = ref('')

const glyphs = ref([
    { baseChar: ' ', glyph: String.fromCodePoint(0x0009), name: 'CHARACTER TABULATION'},
    { baseChar: ' ', glyph: String.fromCodePoint(0x000A), name: 'LINE FEED (LF)'},
    { baseChar: ' ', glyph: String.fromCodePoint(0x000D), name: 'CARRIAGE RETURN (CR)'},
    { baseChar: ' ', glyph: String.fromCodePoint(0x0020), name: 'SPACE'},
    { baseChar: '!', glyph: String.fromCodePoint(0x0021), name: 'EXCLAMATION MARK'},
    { baseChar: '"', glyph: String.fromCodePoint(0x0022), name: 'QUOTATION MARK'},
    { baseChar: '#', glyph: String.fromCodePoint(0x0023), name: 'NUMBER SIGN'},
    { baseChar: '$', glyph: String.fromCodePoint(0x0024), name: 'DOLLAR SIGN'},
    { baseChar: '%', glyph: String.fromCodePoint(0x0025), name: 'PERCENT SIGN'},
    { baseChar: '&', glyph: String.fromCodePoint(0x0026), name: 'AMPERSAND'},
    { baseChar: '\'', glyph: String.fromCodePoint(0x0027), name: 'APOSTROPHE'},
    { baseChar: '(', glyph: String.fromCodePoint(0x0028), name: 'LEFT PARENTHESIS'},
    { baseChar: ')', glyph: String.fromCodePoint(0x0029), name: 'RIGHT PARENTHESIS'},
    { baseChar: '*', glyph: String.fromCodePoint(0x002A), name: 'ASTERISK'},
    { baseChar: '+', glyph: String.fromCodePoint(0x002B), name: 'PLUS SIGN'},
    { baseChar: ',', glyph: String.fromCodePoint(0x002C), name: 'COMMA'},
    { baseChar: '-', glyph: String.fromCodePoint(0x002D), name: 'HYPHEN-MINUS'},
    { baseChar: '.', glyph: String.fromCodePoint(0x002E), name: 'FULL STOP'},
    { baseChar: '/', glyph: String.fromCodePoint(0x002F), name: 'SOLIDUS'},
    { baseChar: '0', glyph: String.fromCodePoint(0x0030), name: 'DIGIT ZERO'},
    { baseChar: '1', glyph: String.fromCodePoint(0x0031), name: 'DIGIT ONE'},
    { baseChar: '2', glyph: String.fromCodePoint(0x0032), name: 'DIGIT TWO'},
    { baseChar: '3', glyph: String.fromCodePoint(0x0033), name: 'DIGIT THREE'},
    { baseChar: '4', glyph: String.fromCodePoint(0x0034), name: 'DIGIT FOUR'},
    { baseChar: '5', glyph: String.fromCodePoint(0x0035), name: 'DIGIT FIVE'},
    { baseChar: '6', glyph: String.fromCodePoint(0x0036), name: 'DIGIT SIX'},
    { baseChar: '7', glyph: String.fromCodePoint(0x0037), name: 'DIGIT SEVEN'},
    { baseChar: '8', glyph: String.fromCodePoint(0x0038), name: 'DIGIT EIGHT'},
    { baseChar: '9', glyph: String.fromCodePoint(0x0039), name: 'DIGIT NINE'},
    { baseChar: ':', glyph: String.fromCodePoint(0x003A), name: 'COLON'},
    { baseChar: ';', glyph: String.fromCodePoint(0x003B), name: 'SEMICOLON'},
    { baseChar: '<', glyph: String.fromCodePoint(0x003C), name: 'LESS-THAN SIGN'},
    { baseChar: '=', glyph: String.fromCodePoint(0x003D), name: 'EQUALS SIGN'},
    { baseChar: '>', glyph: String.fromCodePoint(0x003E), name: 'GREATER-THAN SIGN'},
    { baseChar: '?', glyph: String.fromCodePoint(0x003F), name: 'QUESTION MARK'},
    { baseChar: '@', glyph: String.fromCodePoint(0x0040), name: 'COMMERCIAL AT'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x0041), name: 'LATIN CAPITAL LETTER A'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x0041, 0x030B), name: 'LATIN CAPITAL LETTER A WITH COMBINING DOUBLE ACUTE ACCENT'},
    { baseChar: 'B', glyph: String.fromCodePoint(0x0042), name: 'LATIN CAPITAL LETTER B'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043), name: 'LATIN CAPITAL LETTER C'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0300), name: 'LATIN CAPITAL LETTER C WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0304), name: 'LATIN CAPITAL LETTER C WITH COMBINING MACRON'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0306), name: 'LATIN CAPITAL LETTER C WITH COMBINING BREVE'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0308), name: 'LATIN CAPITAL LETTER C WITH COMBINING DIAERESIS'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0315), name: 'LATIN CAPITAL LETTER C WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0323), name: 'LATIN CAPITAL LETTER C WITH COMBINING DOT BELOW'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0326), name: 'LATIN CAPITAL LETTER C WITH COMBINING COMMA BELOW'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0043, 0x0328, 0x0306), name: 'LATIN CAPITAL LETTER C WITH COMBINING OGONEK AND COMBINING BREVE'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x0044), name: 'LATIN CAPITAL LETTER D'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x0044, 0x0302), name: 'LATIN CAPITAL LETTER D WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x0045), name: 'LATIN CAPITAL LETTER E'},
    { baseChar: 'F', glyph: String.fromCodePoint(0x0046), name: 'LATIN CAPITAL LETTER F'},
    { baseChar: 'F', glyph: String.fromCodePoint(0x0046, 0x0300), name: 'LATIN CAPITAL LETTER F WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'F', glyph: String.fromCodePoint(0x0046, 0x0304), name: 'LATIN CAPITAL LETTER F WITH COMBINING MACRON'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x0047), name: 'LATIN CAPITAL LETTER G'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x0047, 0x0300), name: 'LATIN CAPITAL LETTER G WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x0048), name: 'LATIN CAPITAL LETTER H'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x0048, 0x0304), name: 'LATIN CAPITAL LETTER H WITH COMBINING MACRON'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x0048, 0x0326), name: 'LATIN CAPITAL LETTER H WITH COMBINING COMMA BELOW'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x0048, 0x0331), name: 'LATIN CAPITAL LETTER H WITH COMBINING MACRON BELOW'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x0049), name: 'LATIN CAPITAL LETTER I'},
    { baseChar: 'J', glyph: String.fromCodePoint(0x004A), name: 'LATIN CAPITAL LETTER J'},
    { baseChar: 'J', glyph: String.fromCodePoint(0x004A, 0x0301), name: 'LATIN CAPITAL LETTER J WITH COMBINING ACUTE ACCENT'},
    { baseChar: 'J', glyph: String.fromCodePoint(0x004A, 0x030C), name: 'LATIN CAPITAL LETTER J WITH COMBINING CARON'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B), name: 'LATIN CAPITAL LETTER K'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x0300), name: 'LATIN CAPITAL LETTER K WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x0302), name: 'LATIN CAPITAL LETTER K WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x0304), name: 'LATIN CAPITAL LETTER K WITH COMBINING MACRON'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x0307), name: 'LATIN CAPITAL LETTER K WITH COMBINING DOT ABOVE'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x0315), name: 'LATIN CAPITAL LETTER K WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x031B), name: 'LATIN CAPITAL LETTER K WITH COMBINING HORN'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x0326), name: 'LATIN CAPITAL LETTER K WITH COMBINING COMMA BELOW'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x035F, 0x0048), name: 'LATIN CAPITAL LETTER K WITH COMBINING DOUBLE MACRON BELOW AND LATIN CAPITAL LETTER H'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x004B, 0x035F, 0x0068), name: 'LATIN CAPITAL LETTER K WITH COMBINING DOUBLE MACRON BELOW AND LATIN SMALL LETTER H'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x004C), name: 'LATIN CAPITAL LETTER L'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x004C, 0x0302), name: 'LATIN CAPITAL LETTER L WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x004C, 0x0325), name: 'LATIN CAPITAL LETTER L WITH COMBINING RING BELOW'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x004C, 0x0325, 0x0304), name: 'LATIN CAPITAL LETTER L WITH COMBINING RING BELOW AND COMBINING MACRON'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x004C, 0x0326), name: 'LATIN CAPITAL LETTER L WITH COMBINING COMMA BELOW'},
    { baseChar: 'M', glyph: String.fromCodePoint(0x004D), name: 'LATIN CAPITAL LETTER M'},
    { baseChar: 'M', glyph: String.fromCodePoint(0x004D, 0x0300), name: 'LATIN CAPITAL LETTER M WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'M', glyph: String.fromCodePoint(0x004D, 0x0302), name: 'LATIN CAPITAL LETTER M WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'M', glyph: String.fromCodePoint(0x004D, 0x0306), name: 'LATIN CAPITAL LETTER M WITH COMBINING BREVE'},
    { baseChar: 'M', glyph: String.fromCodePoint(0x004D, 0x0310), name: 'LATIN CAPITAL LETTER M WITH COMBINING CANDRABINDU'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x004E), name: 'LATIN CAPITAL LETTER N'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x004E, 0x0302), name: 'LATIN CAPITAL LETTER N WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x004E, 0x0304), name: 'LATIN CAPITAL LETTER N WITH COMBINING MACRON'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x004E, 0x0306), name: 'LATIN CAPITAL LETTER N WITH COMBINING BREVE'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x004E, 0x0326), name: 'LATIN CAPITAL LETTER N WITH COMBINING COMMA BELOW'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x004F), name: 'LATIN CAPITAL LETTER O'},
    { baseChar: 'P', glyph: String.fromCodePoint(0x0050), name: 'LATIN CAPITAL LETTER P'},
    { baseChar: 'P', glyph: String.fromCodePoint(0x0050, 0x0300), name: 'LATIN CAPITAL LETTER P WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'P', glyph: String.fromCodePoint(0x0050, 0x0304), name: 'LATIN CAPITAL LETTER P WITH COMBINING MACRON'},
    { baseChar: 'P', glyph: String.fromCodePoint(0x0050, 0x0315), name: 'LATIN CAPITAL LETTER P WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'P', glyph: String.fromCodePoint(0x0050, 0x0323), name: 'LATIN CAPITAL LETTER P WITH COMBINING DOT BELOW'},
    { baseChar: 'Q', glyph: String.fromCodePoint(0x0051), name: 'LATIN CAPITAL LETTER Q'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0052), name: 'LATIN CAPITAL LETTER R'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0052, 0x0306), name: 'LATIN CAPITAL LETTER R WITH COMBINING BREVE'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0052, 0x0325), name: 'LATIN CAPITAL LETTER R WITH COMBINING RING BELOW'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0052, 0x0325, 0x0304), name: 'LATIN CAPITAL LETTER R WITH COMBINING RING BELOW AND COMBINING MACRON'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x0053), name: 'LATIN CAPITAL LETTER S'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x0053, 0x0300), name: 'LATIN CAPITAL LETTER S WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x0053, 0x0304), name: 'LATIN CAPITAL LETTER S WITH COMBINING MACRON'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x0053, 0x031B, 0x0304), name: 'LATIN CAPITAL LETTER S WITH COMBINING HORN AND COMBINING MACRON'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x0053, 0x0331), name: 'LATIN CAPITAL LETTER S WITH COMBINING MACRON BELOW'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0054), name: 'LATIN CAPITAL LETTER T'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0054, 0x0300), name: 'LATIN CAPITAL LETTER T WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0054, 0x0304), name: 'LATIN CAPITAL LETTER T WITH COMBINING MACRON'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0054, 0x0308), name: 'LATIN CAPITAL LETTER T WITH COMBINING DIAERESIS'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0054, 0x0315), name: 'LATIN CAPITAL LETTER T WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0054, 0x031B), name: 'LATIN CAPITAL LETTER T WITH COMBINING HORN'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x0055), name: 'LATIN CAPITAL LETTER U'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x0055, 0x0307), name: 'LATIN CAPITAL LETTER U WITH COMBINING DOT ABOVE'},
    { baseChar: 'V', glyph: String.fromCodePoint(0x0056), name: 'LATIN CAPITAL LETTER V'},
    { baseChar: 'W', glyph: String.fromCodePoint(0x0057), name: 'LATIN CAPITAL LETTER W'},
    { baseChar: 'X', glyph: String.fromCodePoint(0x0058), name: 'LATIN CAPITAL LETTER X'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x0059), name: 'LATIN CAPITAL LETTER Y'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x005A), name: 'LATIN CAPITAL LETTER Z'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x005A, 0x0300), name: 'LATIN CAPITAL LETTER Z WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x005A, 0x0304), name: 'LATIN CAPITAL LETTER Z WITH COMBINING MACRON'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x005A, 0x0306), name: 'LATIN CAPITAL LETTER Z WITH COMBINING BREVE'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x005A, 0x0308), name: 'LATIN CAPITAL LETTER Z WITH COMBINING DIAERESIS'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x005A, 0x0327), name: 'LATIN CAPITAL LETTER Z WITH COMBINING CEDILLA'},
    { baseChar: '[', glyph: String.fromCodePoint(0x005B), name: 'LEFT SQUARE BRACKET'},
    { baseChar: '\\', glyph: String.fromCodePoint(0x005C), name: 'REVERSE SOLIDUS'},
    { baseChar: ']', glyph: String.fromCodePoint(0x005D), name: 'RIGHT SQUARE BRACKET'},
    { baseChar: '^', glyph: String.fromCodePoint(0x005E), name: 'CIRCUMFLEX ACCENT'},
    { baseChar: '_', glyph: String.fromCodePoint(0x005F), name: 'LOW LINE'},
    { baseChar: '`', glyph: String.fromCodePoint(0x0060), name: 'GRAVE ACCENT'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x0061), name: 'LATIN SMALL LETTER A'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x0061, 0x030B), name: 'LATIN SMALL LETTER A WITH COMBINING DOUBLE ACUTE ACCENT'},
    { baseChar: 'b', glyph: String.fromCodePoint(0x0062), name: 'LATIN SMALL LETTER B'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063), name: 'LATIN SMALL LETTER C'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0300), name: 'LATIN SMALL LETTER C WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0304), name: 'LATIN SMALL LETTER C WITH COMBINING MACRON'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0306), name: 'LATIN SMALL LETTER C WITH COMBINING BREVE'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0308), name: 'LATIN SMALL LETTER C WITH COMBINING DIAERESIS'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0315), name: 'LATIN SMALL LETTER C WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0323), name: 'LATIN SMALL LETTER C WITH COMBINING DOT BELOW'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0326), name: 'LATIN SMALL LETTER C WITH COMBINING COMMA BELOW'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0063, 0x0328, 0x0306), name: 'LATIN SMALL LETTER C WITH COMBINING OGONEK AND COMBINING BREVE'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x0064), name: 'LATIN SMALL LETTER D'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x0064, 0x0302), name: 'LATIN SMALL LETTER D WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0065), name: 'LATIN SMALL LETTER E'},
    { baseChar: 'f', glyph: String.fromCodePoint(0x0066), name: 'LATIN SMALL LETTER F'},
    { baseChar: 'f', glyph: String.fromCodePoint(0x0066, 0x0300), name: 'LATIN SMALL LETTER F WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'f', glyph: String.fromCodePoint(0x0066, 0x0304), name: 'LATIN SMALL LETTER F WITH COMBINING MACRON'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x0067), name: 'LATIN SMALL LETTER G'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x0067, 0x0300), name: 'LATIN SMALL LETTER G WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x0068), name: 'LATIN SMALL LETTER H'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x0068, 0x0304), name: 'LATIN SMALL LETTER H WITH COMBINING MACRON'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x0068, 0x0326), name: 'LATIN SMALL LETTER H WITH COMBINING COMMA BELOW'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x0069), name: 'LATIN SMALL LETTER I'},
    { baseChar: 'j', glyph: String.fromCodePoint(0x006A), name: 'LATIN SMALL LETTER J'},
    { baseChar: 'j', glyph: String.fromCodePoint(0x006A, 0x0301), name: 'LATIN SMALL LETTER J WITH COMBINING ACUTE ACCENT'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B), name: 'LATIN SMALL LETTER K'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x0300), name: 'LATIN SMALL LETTER K WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x0302), name: 'LATIN SMALL LETTER K WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x0304), name: 'LATIN SMALL LETTER K WITH COMBINING MACRON'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x0307), name: 'LATIN SMALL LETTER K WITH COMBINING DOT ABOVE'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x0315), name: 'LATIN SMALL LETTER K WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x031B), name: 'LATIN SMALL LETTER K WITH COMBINING HORN'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x0326), name: 'LATIN SMALL LETTER K WITH COMBINING COMMA BELOW'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x006B, 0x035F, 0x0068), name: 'LATIN SMALL LETTER K WITH COMBINING DOUBLE MACRON BELOW AND LATIN SMALL LETTER H'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x006C), name: 'LATIN SMALL LETTER L'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x006C, 0x0302), name: 'LATIN SMALL LETTER L WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x006C, 0x0325), name: 'LATIN SMALL LETTER L WITH COMBINING RING BELOW'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x006C, 0x0325, 0x0304), name: 'LATIN SMALL LETTER L WITH COMBINING RING BELOW AND COMBINING MACRON'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x006C, 0x0326), name: 'LATIN SMALL LETTER L WITH COMBINING COMMA BELOW'},
    { baseChar: 'm', glyph: String.fromCodePoint(0x006D), name: 'LATIN SMALL LETTER M'},
    { baseChar: 'm', glyph: String.fromCodePoint(0x006D, 0x0300), name: 'LATIN SMALL LETTER M WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'm', glyph: String.fromCodePoint(0x006D, 0x0302), name: 'LATIN SMALL LETTER M WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'm', glyph: String.fromCodePoint(0x006D, 0x0306), name: 'LATIN SMALL LETTER M WITH COMBINING BREVE'},
    { baseChar: 'm', glyph: String.fromCodePoint(0x006D, 0x0310), name: 'LATIN SMALL LETTER M WITH COMBINING CANDRABINDU'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x006E), name: 'LATIN SMALL LETTER N'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x006E, 0x0302), name: 'LATIN SMALL LETTER N WITH COMBINING CIRCUMFLEX ACCENT'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x006E, 0x0304), name: 'LATIN SMALL LETTER N WITH COMBINING MACRON'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x006E, 0x0306), name: 'LATIN SMALL LETTER N WITH COMBINING BREVE'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x006E, 0x0326), name: 'LATIN SMALL LETTER N WITH COMBINING COMMA BELOW'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x006F), name: 'LATIN SMALL LETTER O'},
    { baseChar: 'p', glyph: String.fromCodePoint(0x0070), name: 'LATIN SMALL LETTER P'},
    { baseChar: 'p', glyph: String.fromCodePoint(0x0070, 0x0300), name: 'LATIN SMALL LETTER P WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'p', glyph: String.fromCodePoint(0x0070, 0x0304), name: 'LATIN SMALL LETTER P WITH COMBINING MACRON'},
    { baseChar: 'p', glyph: String.fromCodePoint(0x0070, 0x0315), name: 'LATIN SMALL LETTER P WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'p', glyph: String.fromCodePoint(0x0070, 0x0323), name: 'LATIN SMALL LETTER P WITH COMBINING DOT BELOW'},
    { baseChar: 'q', glyph: String.fromCodePoint(0x0071), name: 'LATIN SMALL LETTER Q'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0072), name: 'LATIN SMALL LETTER R'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0072, 0x0306), name: 'LATIN SMALL LETTER R WITH COMBINING BREVE'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0072, 0x0325), name: 'LATIN SMALL LETTER R WITH COMBINING RING BELOW'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0072, 0x0325, 0x0304), name: 'LATIN SMALL LETTER R WITH COMBINING RING BELOW AND COMBINING MACRON'},
    { baseChar: 's', glyph: String.fromCodePoint(0x0073), name: 'LATIN SMALL LETTER S'},
    { baseChar: 's', glyph: String.fromCodePoint(0x0073, 0x0300), name: 'LATIN SMALL LETTER S WITH COMBINING GRAVE ACCENT'},
    { baseChar: 's', glyph: String.fromCodePoint(0x0073, 0x0304), name: 'LATIN SMALL LETTER S WITH COMBINING MACRON'},
    { baseChar: 's', glyph: String.fromCodePoint(0x0073, 0x031B, 0x0304), name: 'LATIN SMALL LETTER S WITH COMBINING HORN AND COMBINING MACRON'},
    { baseChar: 's', glyph: String.fromCodePoint(0x0073, 0x0331), name: 'LATIN SMALL LETTER S WITH COMBINING MACRON BELOW'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0074), name: 'LATIN SMALL LETTER T'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0074, 0x0300), name: 'LATIN SMALL LETTER T WITH COMBINING GRAVE ACCENT'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0074, 0x0304), name: 'LATIN SMALL LETTER T WITH COMBINING MACRON'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0074, 0x0315), name: 'LATIN SMALL LETTER T WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0074, 0x031B), name: 'LATIN SMALL LETTER T WITH COMBINING HORN'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x0075), name: 'LATIN SMALL LETTER U'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x0075, 0x0307), name: 'LATIN SMALL LETTER U WITH COMBINING DOT ABOVE'},
    { baseChar: 'v', glyph: String.fromCodePoint(0x0076), name: 'LATIN SMALL LETTER V'},
    { baseChar: 'w', glyph: String.fromCodePoint(0x0077), name: 'LATIN SMALL LETTER W'},
    { baseChar: 'x', glyph: String.fromCodePoint(0x0078), name: 'LATIN SMALL LETTER X'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x0079), name: 'LATIN SMALL LETTER Y'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x007A), name: 'LATIN SMALL LETTER Z'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x007A, 0x0300), name: 'LATIN SMALL LETTER Z WITH COMBINING GRAVE ACCENT'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x007A, 0x0304), name: 'LATIN SMALL LETTER Z WITH COMBINING MACRON'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x007A, 0x0306), name: 'LATIN SMALL LETTER Z WITH COMBINING BREVE'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x007A, 0x0308), name: 'LATIN SMALL LETTER Z WITH COMBINING DIAERESIS'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x007A, 0x0327), name: 'LATIN SMALL LETTER Z WITH COMBINING CEDILLA'},
    { baseChar: '{', glyph: String.fromCodePoint(0x007B), name: 'LEFT CURLY BRACKET'},
    { baseChar: '|', glyph: String.fromCodePoint(0x007C), name: 'VERTICAL LINE'},
    { baseChar: '}', glyph: String.fromCodePoint(0x007D), name: 'RIGHT CURLY BRACKET'},
    { baseChar: '~', glyph: String.fromCodePoint(0x007E), name: 'TILDE'},
    { baseChar: ' ', glyph: String.fromCodePoint(0x00A0), name: 'NO-BREAK SPACE'},
    { baseChar: '¡', glyph: String.fromCodePoint(0x00A1), name: 'INVERTED EXCLAMATION MARK'},
    { baseChar: '¢', glyph: String.fromCodePoint(0x00A2), name: 'CENT SIGN'},
    { baseChar: '£', glyph: String.fromCodePoint(0x00A3), name: 'POUND SIGN'},
    { baseChar: '¤', glyph: String.fromCodePoint(0x00A4), name: 'CURRENCY SIGN'},
    { baseChar: '¥', glyph: String.fromCodePoint(0x00A5), name: 'YEN SIGN'},
    { baseChar: '¦', glyph: String.fromCodePoint(0x00A6), name: 'BROKEN BAR'},
    { baseChar: '§', glyph: String.fromCodePoint(0x00A7), name: 'SECTION SIGN'},
    { baseChar: '¨', glyph: String.fromCodePoint(0x00A8), name: 'DIAERESIS'},
    { baseChar: '©', glyph: String.fromCodePoint(0x00A9), name: 'COPYRIGHT SIGN'},
    { baseChar: 'ª', glyph: String.fromCodePoint(0x00AA), name: 'FEMININE ORDINAL INDICATOR'},
    { baseChar: '«', glyph: String.fromCodePoint(0x00AB), name: 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK'},
    { baseChar: '¬', glyph: String.fromCodePoint(0x00AC), name: 'NOT SIGN'},
    { baseChar: '®', glyph: String.fromCodePoint(0x00AE), name: 'REGISTERED SIGN'},
    { baseChar: '¯', glyph: String.fromCodePoint(0x00AF), name: 'MACRON'},
    { baseChar: '°', glyph: String.fromCodePoint(0x00B0), name: 'DEGREE SIGN'},
    { baseChar: '±', glyph: String.fromCodePoint(0x00B1), name: 'PLUS-MINUS SIGN'},
    { baseChar: '2', glyph: String.fromCodePoint(0x00B2), name: 'SUPERSCRIPT TWO'},
    { baseChar: '3', glyph: String.fromCodePoint(0x00B3), name: 'SUPERSCRIPT THREE'},
    { baseChar: '´', glyph: String.fromCodePoint(0x00B4), name: 'ACUTE ACCENT'},
    { baseChar: 'µ', glyph: String.fromCodePoint(0x00B5), name: 'MICRO SIGN'},
    { baseChar: '¶', glyph: String.fromCodePoint(0x00B6), name: 'PILCROW SIGN'},
    { baseChar: '·', glyph: String.fromCodePoint(0x00B7), name: 'MIDDLE DOT'},
    { baseChar: '¸', glyph: String.fromCodePoint(0x00B8), name: 'CEDILLA'},
    { baseChar: '1', glyph: String.fromCodePoint(0x00B9), name: 'SUPERSCRIPT ONE'},
    { baseChar: 'º', glyph: String.fromCodePoint(0x00BA), name: 'MASCULINE ORDINAL INDICATOR'},
    { baseChar: '»', glyph: String.fromCodePoint(0x00BB), name: 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK'},
    { baseChar: '1', glyph: String.fromCodePoint(0x00BC), name: 'VULGAR FRACTION ONE QUARTER'},
    { baseChar: '1', glyph: String.fromCodePoint(0x00BD), name: 'VULGAR FRACTION ONE HALF'},
    { baseChar: '3', glyph: String.fromCodePoint(0x00BE), name: 'VULGAR FRACTION THREE QUARTERS'},
    { baseChar: '?', glyph: String.fromCodePoint(0x00BF), name: 'INVERTED QUESTION MARK'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x00C0), name: 'LATIN CAPITAL LETTER A WITH GRAVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x00C1), name: 'LATIN CAPITAL LETTER A WITH ACUTE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x00C2), name: 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x00C3), name: 'LATIN CAPITAL LETTER A WITH TILDE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x00C4), name: 'LATIN CAPITAL LETTER A WITH DIAERESIS'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x00C5), name: 'LATIN CAPITAL LETTER A WITH RING ABOVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x00C6), name: 'LATIN CAPITAL LETTER AE'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x00C7), name: 'LATIN CAPITAL LETTER C WITH CEDILLA'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x00C7, 0x0306), name: 'LATIN CAPITAL LETTER C WITH CEDILLA WITH COMBINING BREVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x00C8), name: 'LATIN CAPITAL LETTER E WITH GRAVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x00C9), name: 'LATIN CAPITAL LETTER E WITH ACUTE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x00CA), name: 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x00CB), name: 'LATIN CAPITAL LETTER E WITH DIAERESIS'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x00CC), name: 'LATIN CAPITAL LETTER I WITH GRAVE'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x00CD), name: 'LATIN CAPITAL LETTER I WITH ACUTE'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x00CE), name: 'LATIN CAPITAL LETTER I WITH CIRCUMFLEX'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x00CF), name: 'LATIN CAPITAL LETTER I WITH DIAERESIS'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x00D0), name: 'LATIN CAPITAL LETTER ETH'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x00D1), name: 'LATIN CAPITAL LETTER N WITH TILDE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x00D2), name: 'LATIN CAPITAL LETTER O WITH GRAVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x00D3), name: 'LATIN CAPITAL LETTER O WITH ACUTE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x00D4), name: 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x00D5), name: 'LATIN CAPITAL LETTER O WITH TILDE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x00D6), name: 'LATIN CAPITAL LETTER O WITH DIAERESIS'},
    { baseChar: 'x', glyph: String.fromCodePoint(0x00D7), name: 'MULTIPLICATION SIGN'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x00D8), name: 'LATIN CAPITAL LETTER O WITH STROKE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x00D9), name: 'LATIN CAPITAL LETTER U WITH GRAVE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x00DA), name: 'LATIN CAPITAL LETTER U WITH ACUTE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x00DB), name: 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x00DB, 0x0304), name: 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX WITH COMBINING MACRON'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x00DC), name: 'LATIN CAPITAL LETTER U WITH DIAERESIS'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x00DD), name: 'LATIN CAPITAL LETTER Y WITH ACUTE'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x00DE), name: 'LATIN CAPITAL LETTER THORN'},
    { baseChar: 's', glyph: String.fromCodePoint(0x00DF), name: 'LATIN SMALL LETTER SHARP S'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x00E0), name: 'LATIN SMALL LETTER A WITH GRAVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x00E1), name: 'LATIN SMALL LETTER A WITH ACUTE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x00E2), name: 'LATIN SMALL LETTER A WITH CIRCUMFLEX'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x00E3), name: 'LATIN SMALL LETTER A WITH TILDE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x00E4), name: 'LATIN SMALL LETTER A WITH DIAERESIS'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x00E5), name: 'LATIN SMALL LETTER A WITH RING ABOVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x00E6), name: 'LATIN SMALL LETTER AE'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x00E7), name: 'LATIN SMALL LETTER C WITH CEDILLA'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x00E7, 0x0306), name: 'LATIN SMALL LETTER C WITH CEDILLA WITH COMBINING BREVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x00E8), name: 'LATIN SMALL LETTER E WITH GRAVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x00E9), name: 'LATIN SMALL LETTER E WITH ACUTE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x00EA), name: 'LATIN SMALL LETTER E WITH CIRCUMFLEX'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x00EB), name: 'LATIN SMALL LETTER E WITH DIAERESIS'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x00EC), name: 'LATIN SMALL LETTER I WITH GRAVE'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x00ED), name: 'LATIN SMALL LETTER I WITH ACUTE'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x00EE), name: 'LATIN SMALL LETTER I WITH CIRCUMFLEX'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x00EF), name: 'LATIN SMALL LETTER I WITH DIAERESIS'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x00F0), name: 'LATIN SMALL LETTER ETH'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x00F1), name: 'LATIN SMALL LETTER N WITH TILDE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x00F2), name: 'LATIN SMALL LETTER O WITH GRAVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x00F3), name: 'LATIN SMALL LETTER O WITH ACUTE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x00F4), name: 'LATIN SMALL LETTER O WITH CIRCUMFLEX'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x00F5), name: 'LATIN SMALL LETTER O WITH TILDE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x00F6), name: 'LATIN SMALL LETTER O WITH DIAERESIS'},
    { baseChar: '÷', glyph: String.fromCodePoint(0x00F7), name: 'DIVISION SIGN'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x00F8), name: 'LATIN SMALL LETTER O WITH STROKE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x00F9), name: 'LATIN SMALL LETTER U WITH GRAVE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x00FA), name: 'LATIN SMALL LETTER U WITH ACUTE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x00FB), name: 'LATIN SMALL LETTER U WITH CIRCUMFLEX'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x00FB, 0x0304), name: 'LATIN SMALL LETTER U WITH CIRCUMFLEX WITH COMBINING MACRON'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x00FC), name: 'LATIN SMALL LETTER U WITH DIAERESIS'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x00FD), name: 'LATIN SMALL LETTER Y WITH ACUTE'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x00FE), name: 'LATIN SMALL LETTER THORN'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x00FF), name: 'LATIN SMALL LETTER Y WITH DIAERESIS'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x00FF, 0x0301), name: 'LATIN SMALL LETTER Y WITH DIAERESIS WITH COMBINING ACUTE ACCENT'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x0100), name: 'LATIN CAPITAL LETTER A WITH MACRON'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x0101), name: 'LATIN SMALL LETTER A WITH MACRON'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x0102), name: 'LATIN CAPITAL LETTER A WITH BREVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x0103), name: 'LATIN SMALL LETTER A WITH BREVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x0104), name: 'LATIN CAPITAL LETTER A WITH OGONEK'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x0105), name: 'LATIN SMALL LETTER A WITH OGONEK'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0106), name: 'LATIN CAPITAL LETTER C WITH ACUTE'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0107), name: 'LATIN SMALL LETTER C WITH ACUTE'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0108), name: 'LATIN CAPITAL LETTER C WITH CIRCUMFLEX'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0109), name: 'LATIN SMALL LETTER C WITH CIRCUMFLEX'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x010A), name: 'LATIN CAPITAL LETTER C WITH DOT ABOVE'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x010B), name: 'LATIN SMALL LETTER C WITH DOT ABOVE'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x010C), name: 'LATIN CAPITAL LETTER C WITH CARON'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x010C, 0x0315), name: 'LATIN CAPITAL LETTER C WITH CARON WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x010C, 0x0323), name: 'LATIN CAPITAL LETTER C WITH CARON WITH COMBINING DOT BELOW'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x010D), name: 'LATIN SMALL LETTER C WITH CARON'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x010D, 0x0315), name: 'LATIN SMALL LETTER C WITH CARON WITH COMBINING COMMA ABOVE RIGHT'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x010D, 0x0323), name: 'LATIN SMALL LETTER C WITH CARON WITH COMBINING DOT BELOW'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x010E), name: 'LATIN CAPITAL LETTER D WITH CARON'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x010F), name: 'LATIN SMALL LETTER D WITH CARON'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x0110), name: 'LATIN CAPITAL LETTER D WITH STROKE'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x0111), name: 'LATIN SMALL LETTER D WITH STROKE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x0112), name: 'LATIN CAPITAL LETTER E WITH MACRON'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0113), name: 'LATIN SMALL LETTER E WITH MACRON'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0113, 0x030D), name: 'LATIN SMALL LETTER E WITH MACRON WITH COMBINING VERTICAL LINE ABOVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x0114), name: 'LATIN CAPITAL LETTER E WITH BREVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0115), name: 'LATIN SMALL LETTER E WITH BREVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x0116), name: 'LATIN CAPITAL LETTER E WITH DOT ABOVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0117), name: 'LATIN SMALL LETTER E WITH DOT ABOVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x0118), name: 'LATIN CAPITAL LETTER E WITH OGONEK'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0119), name: 'LATIN SMALL LETTER E WITH OGONEK'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x011A), name: 'LATIN CAPITAL LETTER E WITH CARON'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x011B), name: 'LATIN SMALL LETTER E WITH CARON'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x011C), name: 'LATIN CAPITAL LETTER G WITH CIRCUMFLEX'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x011D), name: 'LATIN SMALL LETTER G WITH CIRCUMFLEX'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x011E), name: 'LATIN CAPITAL LETTER G WITH BREVE'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x011F), name: 'LATIN SMALL LETTER G WITH BREVE'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x0120), name: 'LATIN CAPITAL LETTER G WITH DOT ABOVE'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x0121), name: 'LATIN SMALL LETTER G WITH DOT ABOVE'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x0122), name: 'LATIN CAPITAL LETTER G WITH CEDILLA'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x0123), name: 'LATIN SMALL LETTER G WITH CEDILLA'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x0124), name: 'LATIN CAPITAL LETTER H WITH CIRCUMFLEX'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x0125), name: 'LATIN SMALL LETTER H WITH CIRCUMFLEX'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x0126), name: 'LATIN CAPITAL LETTER H WITH STROKE'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x0127), name: 'LATIN SMALL LETTER H WITH STROKE'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x0128), name: 'LATIN CAPITAL LETTER I WITH TILDE'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x0129), name: 'LATIN SMALL LETTER I WITH TILDE'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x012A), name: 'LATIN CAPITAL LETTER I WITH MACRON'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x012A, 0x0301), name: 'LATIN CAPITAL LETTER I WITH MACRON WITH COMBINING ACUTE ACCENT'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x012B), name: 'LATIN SMALL LETTER I WITH MACRON'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x012B, 0x0301), name: 'LATIN SMALL LETTER I WITH MACRON WITH COMBINING ACUTE ACCENT'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x012C), name: 'LATIN CAPITAL LETTER I WITH BREVE'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x012D), name: 'LATIN SMALL LETTER I WITH BREVE'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x012E), name: 'LATIN CAPITAL LETTER I WITH OGONEK'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x012F), name: 'LATIN SMALL LETTER I WITH OGONEK'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x0130), name: 'LATIN CAPITAL LETTER I WITH DOT ABOVE'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x0131), name: 'LATIN SMALL LETTER DOTLESS I'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x0132), name: 'LATIN CAPITAL LIGATURE IJ'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x0133), name: 'LATIN SMALL LIGATURE IJ'},
    { baseChar: 'J', glyph: String.fromCodePoint(0x0134), name: 'LATIN CAPITAL LETTER J WITH CIRCUMFLEX'},
    { baseChar: 'j', glyph: String.fromCodePoint(0x0135), name: 'LATIN SMALL LETTER J WITH CIRCUMFLEX'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x0136), name: 'LATIN CAPITAL LETTER K WITH CEDILLA'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x0137), name: 'LATIN SMALL LETTER K WITH CEDILLA'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x0138), name: 'LATIN SMALL LETTER KRA'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x0139), name: 'LATIN CAPITAL LETTER L WITH ACUTE'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x013A), name: 'LATIN SMALL LETTER L WITH ACUTE'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x013B), name: 'LATIN CAPITAL LETTER L WITH CEDILLA'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x013C), name: 'LATIN SMALL LETTER L WITH CEDILLA'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x013D), name: 'LATIN CAPITAL LETTER L WITH CARON'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x013E), name: 'LATIN SMALL LETTER L WITH CARON'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x013F), name: 'LATIN CAPITAL LETTER L WITH MIDDLE DOT'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x0140), name: 'LATIN SMALL LETTER L WITH MIDDLE DOT'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x0141), name: 'LATIN CAPITAL LETTER L WITH STROKE'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x0142), name: 'LATIN SMALL LETTER L WITH STROKE'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x0143), name: 'LATIN CAPITAL LETTER N WITH ACUTE'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x0144), name: 'LATIN SMALL LETTER N WITH ACUTE'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x0145), name: 'LATIN CAPITAL LETTER N WITH CEDILLA'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x0146), name: 'LATIN SMALL LETTER N WITH CEDILLA'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x0147), name: 'LATIN CAPITAL LETTER N WITH CARON'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x0148), name: 'LATIN SMALL LETTER N WITH CARON'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x0149), name: 'LATIN SMALL LETTER N PRECEDED BY APOSTROPHE'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x014A), name: 'LATIN CAPITAL LETTER ENG'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x014B), name: 'LATIN SMALL LETTER ENG'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x014C), name: 'LATIN CAPITAL LETTER O WITH MACRON'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x014D), name: 'LATIN SMALL LETTER O WITH MACRON'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x014D, 0x030D), name: 'LATIN SMALL LETTER O WITH MACRON WITH COMBINING VERTICAL LINE ABOVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x014E), name: 'LATIN CAPITAL LETTER O WITH BREVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x014F), name: 'LATIN SMALL LETTER O WITH BREVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x0150), name: 'LATIN CAPITAL LETTER O WITH DOUBLE ACUTE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x0151), name: 'LATIN SMALL LETTER O WITH DOUBLE ACUTE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x0152), name: 'LATIN CAPITAL LIGATURE OE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x0153), name: 'LATIN SMALL LIGATURE OE'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0154), name: 'LATIN CAPITAL LETTER R WITH ACUTE'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0155), name: 'LATIN SMALL LETTER R WITH ACUTE'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0156), name: 'LATIN CAPITAL LETTER R WITH CEDILLA'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0157), name: 'LATIN SMALL LETTER R WITH CEDILLA'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0158), name: 'LATIN CAPITAL LETTER R WITH CARON'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0159), name: 'LATIN SMALL LETTER R WITH CARON'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x015A), name: 'LATIN CAPITAL LETTER S WITH ACUTE'},
    { baseChar: 's', glyph: String.fromCodePoint(0x015B), name: 'LATIN SMALL LETTER S WITH ACUTE'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x015C), name: 'LATIN CAPITAL LETTER S WITH CIRCUMFLEX'},
    { baseChar: 's', glyph: String.fromCodePoint(0x015D), name: 'LATIN SMALL LETTER S WITH CIRCUMFLEX'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x015E), name: 'LATIN CAPITAL LETTER S WITH CEDILLA'},
    { baseChar: 's', glyph: String.fromCodePoint(0x015F), name: 'LATIN SMALL LETTER S WITH CEDILLA'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x0160), name: 'LATIN CAPITAL LETTER S WITH CARON'},
    { baseChar: 's', glyph: String.fromCodePoint(0x0161), name: 'LATIN SMALL LETTER S WITH CARON'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0162), name: 'LATIN CAPITAL LETTER T WITH CEDILLA'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0163), name: 'LATIN SMALL LETTER T WITH CEDILLA'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0164), name: 'LATIN CAPITAL LETTER T WITH CARON'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0165), name: 'LATIN SMALL LETTER T WITH CARON'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x0166), name: 'LATIN CAPITAL LETTER T WITH STROKE'},
    { baseChar: 't', glyph: String.fromCodePoint(0x0167), name: 'LATIN SMALL LETTER T WITH STROKE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x0168), name: 'LATIN CAPITAL LETTER U WITH TILDE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x0169), name: 'LATIN SMALL LETTER U WITH TILDE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x016A), name: 'LATIN CAPITAL LETTER U WITH MACRON'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x016B), name: 'LATIN SMALL LETTER U WITH MACRON'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x016C), name: 'LATIN CAPITAL LETTER U WITH BREVE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x016D), name: 'LATIN SMALL LETTER U WITH BREVE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x016E), name: 'LATIN CAPITAL LETTER U WITH RING ABOVE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x016F), name: 'LATIN SMALL LETTER U WITH RING ABOVE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x0170), name: 'LATIN CAPITAL LETTER U WITH DOUBLE ACUTE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x0171), name: 'LATIN SMALL LETTER U WITH DOUBLE ACUTE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x0172), name: 'LATIN CAPITAL LETTER U WITH OGONEK'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x0173), name: 'LATIN SMALL LETTER U WITH OGONEK'},
    { baseChar: 'W', glyph: String.fromCodePoint(0x0174), name: 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX'},
    { baseChar: 'w', glyph: String.fromCodePoint(0x0175), name: 'LATIN SMALL LETTER W WITH CIRCUMFLEX'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x0176), name: 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x0177), name: 'LATIN SMALL LETTER Y WITH CIRCUMFLEX'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x0178), name: 'LATIN CAPITAL LETTER Y WITH DIAERESIS'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x0179), name: 'LATIN CAPITAL LETTER Z WITH ACUTE'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x017A), name: 'LATIN SMALL LETTER Z WITH ACUTE'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x017B), name: 'LATIN CAPITAL LETTER Z WITH DOT ABOVE'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x017C), name: 'LATIN SMALL LETTER Z WITH DOT ABOVE'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x017D), name: 'LATIN CAPITAL LETTER Z WITH CARON'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x017D, 0x0326), name: 'LATIN CAPITAL LETTER Z WITH CARON WITH COMBINING COMMA BELOW'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x017D, 0x0327), name: 'LATIN CAPITAL LETTER Z WITH CARON WITH COMBINING CEDILLA'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x017E), name: 'LATIN SMALL LETTER Z WITH CARON'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x017E, 0x0326), name: 'LATIN SMALL LETTER Z WITH CARON WITH COMBINING COMMA BELOW'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x017E, 0x0327), name: 'LATIN SMALL LETTER Z WITH CARON WITH COMBINING CEDILLA'},
    { baseChar: 'C', glyph: String.fromCodePoint(0x0187), name: 'LATIN CAPITAL LETTER C WITH HOOK'},
    { baseChar: 'c', glyph: String.fromCodePoint(0x0188), name: 'LATIN SMALL LETTER C WITH HOOK'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x018F), name: 'LATIN CAPITAL LETTER SCHWA'},
    { baseChar: 'f', glyph: String.fromCodePoint(0x0192), name: 'LATIN SMALL LETTER F WITH HOOK'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x0197), name: 'LATIN CAPITAL LETTER I WITH STROKE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x01A0), name: 'LATIN CAPITAL LETTER O WITH HORN'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x01A1), name: 'LATIN SMALL LETTER O WITH HORN'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x01AF), name: 'LATIN CAPITAL LETTER U WITH HORN'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x01B0), name: 'LATIN SMALL LETTER U WITH HORN'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x01B7), name: 'LATIN CAPITAL LETTER EZH'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x01CD), name: 'LATIN CAPITAL LETTER A WITH CARON'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x01CE), name: 'LATIN SMALL LETTER A WITH CARON'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x01CF), name: 'LATIN CAPITAL LETTER I WITH CARON'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x01D0), name: 'LATIN SMALL LETTER I WITH CARON'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x01D1), name: 'LATIN CAPITAL LETTER O WITH CARON'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x01D2), name: 'LATIN SMALL LETTER O WITH CARON'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x01D3), name: 'LATIN CAPITAL LETTER U WITH CARON'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x01D4), name: 'LATIN SMALL LETTER U WITH CARON'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x01D5), name: 'LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x01D6), name: 'LATIN SMALL LETTER U WITH DIAERESIS AND MACRON'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x01D7), name: 'LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x01D8), name: 'LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x01D9), name: 'LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x01DA), name: 'LATIN SMALL LETTER U WITH DIAERESIS AND CARON'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x01DB), name: 'LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x01DC), name: 'LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x01DE), name: 'LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x01DF), name: 'LATIN SMALL LETTER A WITH DIAERESIS AND MACRON'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x01E2), name: 'LATIN CAPITAL LETTER AE WITH MACRON'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x01E3), name: 'LATIN SMALL LETTER AE WITH MACRON'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x01E4), name: 'LATIN CAPITAL LETTER G WITH STROKE'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x01E5), name: 'LATIN SMALL LETTER G WITH STROKE'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x01E6), name: 'LATIN CAPITAL LETTER G WITH CARON'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x01E7), name: 'LATIN SMALL LETTER G WITH CARON'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x01E8), name: 'LATIN CAPITAL LETTER K WITH CARON'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x01E9), name: 'LATIN SMALL LETTER K WITH CARON'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x01EA), name: 'LATIN CAPITAL LETTER O WITH OGONEK'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x01EB), name: 'LATIN SMALL LETTER O WITH OGONEK'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x01EC), name: 'LATIN CAPITAL LETTER O WITH OGONEK AND MACRON'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x01ED), name: 'LATIN SMALL LETTER O WITH OGONEK AND MACRON'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x01EE), name: 'LATIN CAPITAL LETTER EZH WITH CARON'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x01EF), name: 'LATIN SMALL LETTER EZH WITH CARON'},
    { baseChar: 'j', glyph: String.fromCodePoint(0x01F0), name: 'LATIN SMALL LETTER J WITH CARON'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x01F4), name: 'LATIN CAPITAL LETTER G WITH ACUTE'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x01F5), name: 'LATIN SMALL LETTER G WITH ACUTE'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x01F8), name: 'LATIN CAPITAL LETTER N WITH GRAVE'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x01F9), name: 'LATIN SMALL LETTER N WITH GRAVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x01FA), name: 'LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x01FB), name: 'LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x01FC), name: 'LATIN CAPITAL LETTER AE WITH ACUTE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x01FD), name: 'LATIN SMALL LETTER AE WITH ACUTE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x01FE), name: 'LATIN CAPITAL LETTER O WITH STROKE AND ACUTE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x01FF), name: 'LATIN SMALL LETTER O WITH STROKE AND ACUTE'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x0212), name: 'LATIN CAPITAL LETTER R WITH INVERTED BREVE'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x0213), name: 'LATIN SMALL LETTER R WITH INVERTED BREVE'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x0218), name: 'LATIN CAPITAL LETTER S WITH COMMA BELOW'},
    { baseChar: 's', glyph: String.fromCodePoint(0x0219), name: 'LATIN SMALL LETTER S WITH COMMA BELOW'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x021A), name: 'LATIN CAPITAL LETTER T WITH COMMA BELOW'},
    { baseChar: 't', glyph: String.fromCodePoint(0x021B), name: 'LATIN SMALL LETTER T WITH COMMA BELOW'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x021E), name: 'LATIN CAPITAL LETTER H WITH CARON'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x021F), name: 'LATIN SMALL LETTER H WITH CARON'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x0227), name: 'LATIN SMALL LETTER A WITH DOT ABOVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x0228), name: 'LATIN CAPITAL LETTER E WITH CEDILLA'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0229), name: 'LATIN SMALL LETTER E WITH CEDILLA'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x022A), name: 'LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x022B), name: 'LATIN SMALL LETTER O WITH DIAERESIS AND MACRON'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x022C), name: 'LATIN CAPITAL LETTER O WITH TILDE AND MACRON'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x022D), name: 'LATIN SMALL LETTER O WITH TILDE AND MACRON'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x022E), name: 'LATIN CAPITAL LETTER O WITH DOT ABOVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x022F), name: 'LATIN SMALL LETTER O WITH DOT ABOVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x0230), name: 'LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x0231), name: 'LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x0232), name: 'LATIN CAPITAL LETTER Y WITH MACRON'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x0233), name: 'LATIN SMALL LETTER Y WITH MACRON'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x0259), name: 'LATIN SMALL LETTER SCHWA'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x0268), name: 'LATIN SMALL LETTER I WITH STROKE'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x0292), name: 'LATIN SMALL LETTER EZH'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x02B0), name: 'MODIFIER LETTER SMALL H'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x02B3), name: 'MODIFIER LETTER SMALL R'},
    { baseChar: '\'', glyph: String.fromCodePoint(0x02B9), name: 'MODIFIER LETTER PRIME'},
    { baseChar: '"', glyph: String.fromCodePoint(0x02BA), name: 'MODIFIER LETTER DOUBLE PRIME'},
    { baseChar: '\'', glyph: String.fromCodePoint(0x02BE), name: 'MODIFIER LETTER RIGHT HALF RING'},
    { baseChar: '\'', glyph: String.fromCodePoint(0x02BF), name: 'MODIFIER LETTER LEFT HALF RING'},
    { baseChar: 'ˆ', glyph: String.fromCodePoint(0x02C6), name: 'MODIFIER LETTER CIRCUMFLEX ACCENT'},
    { baseChar: '\'', glyph: String.fromCodePoint(0x02C8), name: 'MODIFIER LETTER VERTICAL LINE'},
    { baseChar: ',', glyph: String.fromCodePoint(0x02CC), name: 'MODIFIER LETTER LOW VERTICAL LINE'},
    { baseChar: '˜', glyph: String.fromCodePoint(0x02DC), name: 'SMALL TILDE'},
    { baseChar: 's', glyph: String.fromCodePoint(0x02E2), name: 'MODIFIER LETTER SMALL S'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x1D48), name: 'MODIFIER LETTER SMALL D'},
    { baseChar: 't', glyph: String.fromCodePoint(0x1D57), name: 'MODIFIER LETTER SMALL T'},
    { baseChar: 'B', glyph: String.fromCodePoint(0x1E02), name: 'LATIN CAPITAL LETTER B WITH DOT ABOVE'},
    { baseChar: 'b', glyph: String.fromCodePoint(0x1E03), name: 'LATIN SMALL LETTER B WITH DOT ABOVE'},
    { baseChar: 'B', glyph: String.fromCodePoint(0x1E06), name: 'LATIN CAPITAL LETTER B WITH LINE BELOW'},
    { baseChar: 'b', glyph: String.fromCodePoint(0x1E07), name: 'LATIN SMALL LETTER B WITH LINE BELOW'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x1E0A), name: 'LATIN CAPITAL LETTER D WITH DOT ABOVE'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x1E0B), name: 'LATIN SMALL LETTER D WITH DOT ABOVE'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x1E0C), name: 'LATIN CAPITAL LETTER D WITH DOT BELOW'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x1E0D), name: 'LATIN SMALL LETTER D WITH DOT BELOW'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x1E0E), name: 'LATIN CAPITAL LETTER D WITH LINE BELOW'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x1E0F), name: 'LATIN SMALL LETTER D WITH LINE BELOW'},
    { baseChar: 'D', glyph: String.fromCodePoint(0x1E10), name: 'LATIN CAPITAL LETTER D WITH CEDILLA'},
    { baseChar: 'd', glyph: String.fromCodePoint(0x1E11), name: 'LATIN SMALL LETTER D WITH CEDILLA'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1E17), name: 'LATIN SMALL LETTER E WITH MACRON AND ACUTE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1E1C), name: 'LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1E1D), name: 'LATIN SMALL LETTER E WITH CEDILLA AND BREVE'},
    { baseChar: 'F', glyph: String.fromCodePoint(0x1E1E), name: 'LATIN CAPITAL LETTER F WITH DOT ABOVE'},
    { baseChar: 'f', glyph: String.fromCodePoint(0x1E1F), name: 'LATIN SMALL LETTER F WITH DOT ABOVE'},
    { baseChar: 'G', glyph: String.fromCodePoint(0x1E20), name: 'LATIN CAPITAL LETTER G WITH MACRON'},
    { baseChar: 'g', glyph: String.fromCodePoint(0x1E21), name: 'LATIN SMALL LETTER G WITH MACRON'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x1E22), name: 'LATIN CAPITAL LETTER H WITH DOT ABOVE'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x1E23), name: 'LATIN SMALL LETTER H WITH DOT ABOVE'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x1E24), name: 'LATIN CAPITAL LETTER H WITH DOT BELOW'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x1E25), name: 'LATIN SMALL LETTER H WITH DOT BELOW'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x1E26), name: 'LATIN CAPITAL LETTER H WITH DIAERESIS'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x1E27), name: 'LATIN SMALL LETTER H WITH DIAERESIS'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x1E28), name: 'LATIN CAPITAL LETTER H WITH CEDILLA'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x1E29), name: 'LATIN SMALL LETTER H WITH CEDILLA'},
    { baseChar: 'H', glyph: String.fromCodePoint(0x1E2A), name: 'LATIN CAPITAL LETTER H WITH BREVE BELOW'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x1E2B), name: 'LATIN SMALL LETTER H WITH BREVE BELOW'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x1E2F), name: 'LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x1E30), name: 'LATIN CAPITAL LETTER K WITH ACUTE'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x1E31), name: 'LATIN SMALL LETTER K WITH ACUTE'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x1E32), name: 'LATIN CAPITAL LETTER K WITH DOT BELOW'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x1E32, 0x0304), name: 'LATIN CAPITAL LETTER K WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x1E33), name: 'LATIN SMALL LETTER K WITH DOT BELOW'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x1E33, 0x0304), name: 'LATIN SMALL LETTER K WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 'K', glyph: String.fromCodePoint(0x1E34), name: 'LATIN CAPITAL LETTER K WITH LINE BELOW'},
    { baseChar: 'k', glyph: String.fromCodePoint(0x1E35), name: 'LATIN SMALL LETTER K WITH LINE BELOW'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x1E36), name: 'LATIN CAPITAL LETTER L WITH DOT BELOW'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x1E37), name: 'LATIN SMALL LETTER L WITH DOT BELOW'},
    { baseChar: 'L', glyph: String.fromCodePoint(0x1E3A), name: 'LATIN CAPITAL LETTER L WITH LINE BELOW'},
    { baseChar: 'l', glyph: String.fromCodePoint(0x1E3B), name: 'LATIN SMALL LETTER L WITH LINE BELOW'},
    { baseChar: 'M', glyph: String.fromCodePoint(0x1E40), name: 'LATIN CAPITAL LETTER M WITH DOT ABOVE'},
    { baseChar: 'm', glyph: String.fromCodePoint(0x1E41), name: 'LATIN SMALL LETTER M WITH DOT ABOVE'},
    { baseChar: 'M', glyph: String.fromCodePoint(0x1E42), name: 'LATIN CAPITAL LETTER M WITH DOT BELOW'},
    { baseChar: 'm', glyph: String.fromCodePoint(0x1E43), name: 'LATIN SMALL LETTER M WITH DOT BELOW'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x1E44), name: 'LATIN CAPITAL LETTER N WITH DOT ABOVE'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x1E45), name: 'LATIN SMALL LETTER N WITH DOT ABOVE'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x1E46), name: 'LATIN CAPITAL LETTER N WITH DOT BELOW'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x1E47), name: 'LATIN SMALL LETTER N WITH DOT BELOW'},
    { baseChar: 'N', glyph: String.fromCodePoint(0x1E48), name: 'LATIN CAPITAL LETTER N WITH LINE BELOW'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x1E49), name: 'LATIN SMALL LETTER N WITH LINE BELOW'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1E52), name: 'LATIN CAPITAL LETTER O WITH MACRON AND ACUTE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1E53), name: 'LATIN SMALL LETTER O WITH MACRON AND ACUTE'},
    { baseChar: 'P', glyph: String.fromCodePoint(0x1E54), name: 'LATIN CAPITAL LETTER P WITH ACUTE'},
    { baseChar: 'p', glyph: String.fromCodePoint(0x1E55), name: 'LATIN SMALL LETTER P WITH ACUTE'},
    { baseChar: 'P', glyph: String.fromCodePoint(0x1E56), name: 'LATIN CAPITAL LETTER P WITH DOT ABOVE'},
    { baseChar: 'p', glyph: String.fromCodePoint(0x1E57), name: 'LATIN SMALL LETTER P WITH DOT ABOVE'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x1E58), name: 'LATIN CAPITAL LETTER R WITH DOT ABOVE'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x1E59), name: 'LATIN SMALL LETTER R WITH DOT ABOVE'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x1E5A), name: 'LATIN CAPITAL LETTER R WITH DOT BELOW'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x1E5B), name: 'LATIN SMALL LETTER R WITH DOT BELOW'},
    { baseChar: 'R', glyph: String.fromCodePoint(0x1E5E), name: 'LATIN CAPITAL LETTER R WITH LINE BELOW'},
    { baseChar: 'r', glyph: String.fromCodePoint(0x1E5F), name: 'LATIN SMALL LETTER R WITH LINE BELOW'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x1E60), name: 'LATIN CAPITAL LETTER S WITH DOT ABOVE'},
    { baseChar: 's', glyph: String.fromCodePoint(0x1E61), name: 'LATIN SMALL LETTER S WITH DOT ABOVE'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x1E62), name: 'LATIN CAPITAL LETTER S WITH DOT BELOW'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x1E62, 0x0304), name: 'LATIN CAPITAL LETTER S WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 's', glyph: String.fromCodePoint(0x1E63), name: 'LATIN SMALL LETTER S WITH DOT BELOW'},
    { baseChar: 's', glyph: String.fromCodePoint(0x1E63, 0x0304), name: 'LATIN SMALL LETTER S WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x1E6A), name: 'LATIN CAPITAL LETTER T WITH DOT ABOVE'},
    { baseChar: 't', glyph: String.fromCodePoint(0x1E6B), name: 'LATIN SMALL LETTER T WITH DOT ABOVE'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x1E6C), name: 'LATIN CAPITAL LETTER T WITH DOT BELOW'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x1E6C, 0x0304), name: 'LATIN CAPITAL LETTER T WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 't', glyph: String.fromCodePoint(0x1E6D), name: 'LATIN SMALL LETTER T WITH DOT BELOW'},
    { baseChar: 't', glyph: String.fromCodePoint(0x1E6D, 0x0304), name: 'LATIN SMALL LETTER T WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x1E6E), name: 'LATIN CAPITAL LETTER T WITH LINE BELOW'},
    { baseChar: 't', glyph: String.fromCodePoint(0x1E6F), name: 'LATIN SMALL LETTER T WITH LINE BELOW'},
    { baseChar: 'W', glyph: String.fromCodePoint(0x1E80), name: 'LATIN CAPITAL LETTER W WITH GRAVE'},
    { baseChar: 'w', glyph: String.fromCodePoint(0x1E81), name: 'LATIN SMALL LETTER W WITH GRAVE'},
    { baseChar: 'W', glyph: String.fromCodePoint(0x1E82), name: 'LATIN CAPITAL LETTER W WITH ACUTE'},
    { baseChar: 'w', glyph: String.fromCodePoint(0x1E83), name: 'LATIN SMALL LETTER W WITH ACUTE'},
    { baseChar: 'W', glyph: String.fromCodePoint(0x1E84), name: 'LATIN CAPITAL LETTER W WITH DIAERESIS'},
    { baseChar: 'w', glyph: String.fromCodePoint(0x1E85), name: 'LATIN SMALL LETTER W WITH DIAERESIS'},
    { baseChar: 'W', glyph: String.fromCodePoint(0x1E86), name: 'LATIN CAPITAL LETTER W WITH DOT ABOVE'},
    { baseChar: 'w', glyph: String.fromCodePoint(0x1E87), name: 'LATIN SMALL LETTER W WITH DOT ABOVE'},
    { baseChar: 'X', glyph: String.fromCodePoint(0x1E8C), name: 'LATIN CAPITAL LETTER X WITH DIAERESIS'},
    { baseChar: 'x', glyph: String.fromCodePoint(0x1E8D), name: 'LATIN SMALL LETTER X WITH DIAERESIS'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x1E8E), name: 'LATIN CAPITAL LETTER Y WITH DOT ABOVE'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x1E8F), name: 'LATIN SMALL LETTER Y WITH DOT ABOVE'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x1E90), name: 'LATIN CAPITAL LETTER Z WITH CIRCUMFLEX'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x1E91), name: 'LATIN SMALL LETTER Z WITH CIRCUMFLEX'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x1E92), name: 'LATIN CAPITAL LETTER Z WITH DOT BELOW'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x1E93), name: 'LATIN SMALL LETTER Z WITH DOT BELOW'},
    { baseChar: 'Z', glyph: String.fromCodePoint(0x1E94), name: 'LATIN CAPITAL LETTER Z WITH LINE BELOW'},
    { baseChar: 'z', glyph: String.fromCodePoint(0x1E95), name: 'LATIN SMALL LETTER Z WITH LINE BELOW'},
    { baseChar: 'h', glyph: String.fromCodePoint(0x1E96), name: 'LATIN SMALL LETTER H WITH LINE BELOW'},
    { baseChar: 't', glyph: String.fromCodePoint(0x1E97), name: 'LATIN SMALL LETTER T WITH DIAERESIS'},
    { baseChar: 'S', glyph: String.fromCodePoint(0x1E9E), name: 'LATIN CAPITAL LETTER SHARP S'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EA0), name: 'LATIN CAPITAL LETTER A WITH DOT BELOW'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EA0, 0x0308), name: 'LATIN CAPITAL LETTER A WITH DOT BELOW WITH COMBINING DIAERESIS'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EA1), name: 'LATIN SMALL LETTER A WITH DOT BELOW'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EA1, 0x0308), name: 'LATIN SMALL LETTER A WITH DOT BELOW WITH COMBINING DIAERESIS'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EA2), name: 'LATIN CAPITAL LETTER A WITH HOOK ABOVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EA3), name: 'LATIN SMALL LETTER A WITH HOOK ABOVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EA4), name: 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EA5), name: 'LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EA6), name: 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EA7), name: 'LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EA8), name: 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EA9), name: 'LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EAA), name: 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EAB), name: 'LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EAC), name: 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EAD), name: 'LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EAE), name: 'LATIN CAPITAL LETTER A WITH BREVE AND ACUTE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EAF), name: 'LATIN SMALL LETTER A WITH BREVE AND ACUTE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EB0), name: 'LATIN CAPITAL LETTER A WITH BREVE AND GRAVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EB1), name: 'LATIN SMALL LETTER A WITH BREVE AND GRAVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EB2), name: 'LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EB3), name: 'LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EB4), name: 'LATIN CAPITAL LETTER A WITH BREVE AND TILDE'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EB5), name: 'LATIN SMALL LETTER A WITH BREVE AND TILDE'},
    { baseChar: 'A', glyph: String.fromCodePoint(0x1EB6), name: 'LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW'},
    { baseChar: 'a', glyph: String.fromCodePoint(0x1EB7), name: 'LATIN SMALL LETTER A WITH BREVE AND DOT BELOW'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EB8), name: 'LATIN CAPITAL LETTER E WITH DOT BELOW'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EB9), name: 'LATIN SMALL LETTER E WITH DOT BELOW'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EBA), name: 'LATIN CAPITAL LETTER E WITH HOOK ABOVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EBB), name: 'LATIN SMALL LETTER E WITH HOOK ABOVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EBC), name: 'LATIN CAPITAL LETTER E WITH TILDE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EBD), name: 'LATIN SMALL LETTER E WITH TILDE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EBE), name: 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EBF), name: 'LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EC0), name: 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EC1), name: 'LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EC2), name: 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EC3), name: 'LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EC4), name: 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EC5), name: 'LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE'},
    { baseChar: 'E', glyph: String.fromCodePoint(0x1EC6), name: 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW'},
    { baseChar: 'e', glyph: String.fromCodePoint(0x1EC7), name: 'LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x1EC8), name: 'LATIN CAPITAL LETTER I WITH HOOK ABOVE'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x1EC9), name: 'LATIN SMALL LETTER I WITH HOOK ABOVE'},
    { baseChar: 'I', glyph: String.fromCodePoint(0x1ECA), name: 'LATIN CAPITAL LETTER I WITH DOT BELOW'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x1ECB), name: 'LATIN SMALL LETTER I WITH DOT BELOW'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ECC), name: 'LATIN CAPITAL LETTER O WITH DOT BELOW'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ECC, 0x0308), name: 'LATIN CAPITAL LETTER O WITH DOT BELOW WITH COMBINING DIAERESIS'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ECD), name: 'LATIN SMALL LETTER O WITH DOT BELOW'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ECD, 0x0308), name: 'LATIN SMALL LETTER O WITH DOT BELOW WITH COMBINING DIAERESIS'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ECE), name: 'LATIN CAPITAL LETTER O WITH HOOK ABOVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ECF), name: 'LATIN SMALL LETTER O WITH HOOK ABOVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ED0), name: 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ED1), name: 'LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ED2), name: 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ED3), name: 'LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ED4), name: 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ED5), name: 'LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ED6), name: 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ED7), name: 'LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1ED8), name: 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1ED9), name: 'LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1EDA), name: 'LATIN CAPITAL LETTER O WITH HORN AND ACUTE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1EDB), name: 'LATIN SMALL LETTER O WITH HORN AND ACUTE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1EDC), name: 'LATIN CAPITAL LETTER O WITH HORN AND GRAVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1EDD), name: 'LATIN SMALL LETTER O WITH HORN AND GRAVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1EDE), name: 'LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1EDF), name: 'LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1EE0), name: 'LATIN CAPITAL LETTER O WITH HORN AND TILDE'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1EE1), name: 'LATIN SMALL LETTER O WITH HORN AND TILDE'},
    { baseChar: 'O', glyph: String.fromCodePoint(0x1EE2), name: 'LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW'},
    { baseChar: 'o', glyph: String.fromCodePoint(0x1EE3), name: 'LATIN SMALL LETTER O WITH HORN AND DOT BELOW'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EE4), name: 'LATIN CAPITAL LETTER U WITH DOT BELOW'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EE4, 0x0304), name: 'LATIN CAPITAL LETTER U WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EE4, 0x0308), name: 'LATIN CAPITAL LETTER U WITH DOT BELOW WITH COMBINING DIAERESIS'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EE5), name: 'LATIN SMALL LETTER U WITH DOT BELOW'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EE5, 0x0304), name: 'LATIN SMALL LETTER U WITH DOT BELOW WITH COMBINING MACRON'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EE5, 0x0308), name: 'LATIN SMALL LETTER U WITH DOT BELOW WITH COMBINING DIAERESIS'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EE6), name: 'LATIN CAPITAL LETTER U WITH HOOK ABOVE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EE7), name: 'LATIN SMALL LETTER U WITH HOOK ABOVE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EE8), name: 'LATIN CAPITAL LETTER U WITH HORN AND ACUTE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EE9), name: 'LATIN SMALL LETTER U WITH HORN AND ACUTE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EEA), name: 'LATIN CAPITAL LETTER U WITH HORN AND GRAVE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EEB), name: 'LATIN SMALL LETTER U WITH HORN AND GRAVE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EEC), name: 'LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EED), name: 'LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EEE), name: 'LATIN CAPITAL LETTER U WITH HORN AND TILDE'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EEF), name: 'LATIN SMALL LETTER U WITH HORN AND TILDE'},
    { baseChar: 'U', glyph: String.fromCodePoint(0x1EF0), name: 'LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW'},
    { baseChar: 'u', glyph: String.fromCodePoint(0x1EF1), name: 'LATIN SMALL LETTER U WITH HORN AND DOT BELOW'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x1EF2), name: 'LATIN CAPITAL LETTER Y WITH GRAVE'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x1EF3), name: 'LATIN SMALL LETTER Y WITH GRAVE'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x1EF4), name: 'LATIN CAPITAL LETTER Y WITH DOT BELOW'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x1EF5), name: 'LATIN SMALL LETTER Y WITH DOT BELOW'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x1EF6), name: 'LATIN CAPITAL LETTER Y WITH HOOK ABOVE'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x1EF7), name: 'LATIN SMALL LETTER Y WITH HOOK ABOVE'},
    { baseChar: 'Y', glyph: String.fromCodePoint(0x1EF8), name: 'LATIN CAPITAL LETTER Y WITH TILDE'},
    { baseChar: 'y', glyph: String.fromCodePoint(0x1EF9), name: 'LATIN SMALL LETTER Y WITH TILDE'},
    { baseChar: '‘', glyph: String.fromCodePoint(0x2018), name: 'LEFT SINGLE QUOTATION MARK'},
    { baseChar: '’', glyph: String.fromCodePoint(0x2019), name: 'RIGHT SINGLE QUOTATION MARK'},
    { baseChar: '‚', glyph: String.fromCodePoint(0x201A), name: 'SINGLE LOW-9 QUOTATION MARK'},
    { baseChar: '"', glyph: String.fromCodePoint(0x201C), name: 'LEFT DOUBLE QUOTATION MARK'},
    { baseChar: '"', glyph: String.fromCodePoint(0x201D), name: 'RIGHT DOUBLE QUOTATION MARK'},
    { baseChar: '"', glyph: String.fromCodePoint(0x201E), name: 'DOUBLE LOW-9 QUOTATION MARK'},
    { baseChar: '+', glyph: String.fromCodePoint(0x2020), name: 'DAGGER'},
    { baseChar: '+', glyph: String.fromCodePoint(0x2021), name: 'DOUBLE DAGGER'},
    { baseChar: '.', glyph: String.fromCodePoint(0x2026), name: 'HORIZONTAL ELLIPSIS'},
    { baseChar: '%', glyph: String.fromCodePoint(0x2030), name: 'PER MILLE SIGN'},
    { baseChar: '\'', glyph: String.fromCodePoint(0x2032), name: 'PRIME'},
    { baseChar: '\'', glyph: String.fromCodePoint(0x2033), name: 'DOUBLE PRIME'},
    { baseChar: '<', glyph: String.fromCodePoint(0x2039), name: 'SINGLE LEFT-POINTING ANGLE QUOTATION MARK'},
    { baseChar: '>', glyph: String.fromCodePoint(0x203A), name: 'SINGLE RIGHT-POINTING ANGLE QUOTATION MARK'},
    { baseChar: '0', glyph: String.fromCodePoint(0x2070), name: 'SUPERSCRIPT ZERO'},
    { baseChar: '4', glyph: String.fromCodePoint(0x2074), name: 'SUPERSCRIPT FOUR'},
    { baseChar: '5', glyph: String.fromCodePoint(0x2075), name: 'SUPERSCRIPT FIVE'},
    { baseChar: '6', glyph: String.fromCodePoint(0x2076), name: 'SUPERSCRIPT SIX'},
    { baseChar: '7', glyph: String.fromCodePoint(0x2077), name: 'SUPERSCRIPT SEVEN'},
    { baseChar: '8', glyph: String.fromCodePoint(0x2078), name: 'SUPERSCRIPT EIGHT'},
    { baseChar: '9', glyph: String.fromCodePoint(0x2079), name: 'SUPERSCRIPT NINE'},
    { baseChar: 'n', glyph: String.fromCodePoint(0x207F), name: 'SUPERSCRIPT LATIN SMALL LETTER N'},
    { baseChar: '0', glyph: String.fromCodePoint(0x2080), name: 'SUBSCRIPT ZERO'},
    { baseChar: '1', glyph: String.fromCodePoint(0x2081), name: 'SUBSCRIPT ONE'},
    { baseChar: '2', glyph: String.fromCodePoint(0x2082), name: 'SUBSCRIPT TWO'},
    { baseChar: '3', glyph: String.fromCodePoint(0x2083), name: 'SUBSCRIPT THREE'},
    { baseChar: '4', glyph: String.fromCodePoint(0x2084), name: 'SUBSCRIPT FOUR'},
    { baseChar: '5', glyph: String.fromCodePoint(0x2085), name: 'SUBSCRIPT FIVE'},
    { baseChar: '6', glyph: String.fromCodePoint(0x2086), name: 'SUBSCRIPT SIX'},
    { baseChar: '7', glyph: String.fromCodePoint(0x2087), name: 'SUBSCRIPT SEVEN'},
    { baseChar: '8', glyph: String.fromCodePoint(0x2088), name: 'SUBSCRIPT EIGHT'},
    { baseChar: '9', glyph: String.fromCodePoint(0x2089), name: 'SUBSCRIPT NINE'},
    { baseChar: '€', glyph: String.fromCodePoint(0x20AC), name: 'EURO SIGN'},
    { baseChar: 'T', glyph: String.fromCodePoint(0x2122), name: 'TRADE MARK SIGN'},
    { baseChar: 'i', glyph: String.fromCodePoint(0x221E), name: 'INFINITY'},
    { baseChar: '<', glyph: String.fromCodePoint(0x2264), name: 'LESS-THAN OR EQUAL TO'},
    { baseChar: '>', glyph: String.fromCodePoint(0x2265), name: 'GREATER-THAN OR EQUAL TO'}
])

const filteredGrlyphs = computed(() => {
    if (filterChar.value == '') {
        return glyphs.value
    } else {
        return glyphs.value.filter((g) => g.baseChar === filterChar.value.toLowerCase())
    }
})

function glyphClick(glyph) {
    emit('glyph', glyph.glyph)
}
</script>

<template>
    <p>Type a character to show only characters based on it.</p>
    <scale-text-field id="filterField" 
        v-model="filterChar"
        label="Base char"
        max-length="1">
    </scale-text-field>
    <scale-table striped>
        <table>
            <caption v-if="filterChar">
                Text elements based on character <strong>{{ filterChar }}</strong>.
            </caption>
            <thead>
                <tr>
                    <th aria-disabled="true">Text element</th>
                    <th aria-disabled="true">Name</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="g in filteredGrlyphs">
                    <td>
                        <scale-button size="small" @click="() => glyphClick(g)">
                            {{ g.glyph }}
                        </scale-button>
                    </td>
                    <td>{{ g.name }}</td>
                </tr>
            </tbody>
        </table>
    </scale-table>
</template>

<style>
#filterField {
    margin: 5em;
}
td {
    text-align: left;
}
</style>